In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

pd.set_option("display.max_columns", None)

In [9]:
df = pd.read_csv('preprocessed_total_0603.csv')

In [10]:
df.head(2)

,car_url,car_area,car_no,car_brand,nation,car_name,name_datailed,new_price,price,year,use,depreciation,mileage,fuel,forecast_min,forecast_max,car_type,car_cc,color,trans,loss,flood,usage,change,insurance,sales_corp,sales_loca,lat,lng,options,options_count
0,22274652,경기,29너6142,한국GM,국산,한국GM 쉐보레 올란도,LPG LS 일반형,2122,849,2013,103,60,131493,LPG,535,750,RV,0,인기색상,오토,없음,없음,없음,1,있음,주식회사 노빌리티 경기지점,경기 수원시,37.263332,127.028747,[],0
1,22274154,광주,156서1980,한국GM,국산,한국GM 더 뉴 트랙스,1.6 디젤 LT 기본형,1986,1450,2018,52,27,60000,디젤,1104,1533,SUV,1598,회색,오토,없음,없음,있음,2,없음,주식회사 즐거운모터스,광주 서구,35.152140,126.890056,"['주차감지센서', '가죽시트', '열선시트', '사이드커튼에어백', '전동접이사이...",7

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90802 entries, 0 to 90801
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   car_url        90802 non-null  int64
 1   car_area       90802 non-null  object
 2   car_no         90802 non-null  object
 3   car_brand      90802 non-null  object
 4   nation         90802 non-null  object
 5   car_name       90802 non-null  object
 6   name_datailed  90802 non-null  object
 7   new_price      90802 non-null  int64
 8   price          90802 non-null  int64
 9   year           90802 non-null  int64
 10  use            90802 non-null  int64
 11  depreciation   90802 non-null  int64
 12  mileage        90802 non-null  int64
 13  fuel           90802 non-null  object
 14  forecast_min   90802 non-null  int64
 15  forecast_max   90802 non-null  int64
 16  car_type       90802 non-null  object
 17  car_cc         90802 non-null  int64
 18  color          90802 non-null  object
 19  trans          90802 non-null  object
 20  loss           90802 non-null  object
 21  flood          90802 non-null  object
 22  usage          90802 non-null  object
 23  change         90802 non-null  int64
 24  insurance      90802 non-null  object
 25  sales_corp     90802 non-null  object
 26  sales_loca     90802 non-null  object
 27  lat            90802 non-null  float64
 28  lng            90802 non-null  float64
 29  options        90802 non-null  object
 30  options_count  90802 non-null  int64
dtypes: float64(2), int64(12), object(17)
memory usage: 21.5+ MB

# 여기서 부터 모델명으로 통합전처리

In [12]:
df.insert(5,'car_model','')

In [13]:
df.head(2)

,car_url,car_area,car_no,car_brand,nation,car_model,car_name,name_datailed,new_price,price,year,use,depreciation,mileage,fuel,forecast_min,forecast_max,car_type,car_cc,color,trans,loss,flood,usage,change,insurance,sales_corp,sales_loca,lat,lng,options,options_count
0,22274652,경기,29너6142,한국GM,국산,,한국GM 쉐보레 올란도,LPG LS 일반형,2122,849,2013,103,60,131493,LPG,535,750,RV,0,인기색상,오토,없음,없음,없음,1,있음,주식회사 노빌리티 경기지점,경기 수원시,37.263332,127.028747,[],0
1,22274154,광주,156서1980,한국GM,국산,,한국GM 더 뉴 트랙스,1.6 디젤 LT 기본형,1986,1450,2018,52,27,60000,디젤,1104,1533,SUV,1598,회색,오토,없음,없음,있음,2,없음,주식회사 즐거운모터스,광주 서구,35.152140,126.890056,"['주차감지센서', '가죽시트', '열선시트', '사이드커튼에어백', '전동접이사이...",7

### 1~3 완성

In [177]:
df[df['car_name'].str.contains('쏘나타')].index

Int64Index([44249, 44253, 44256, 44263, 44272, 44281, 44284, 44288, 44290,
            44303,
            ...
            65844, 65862, 65869, 65870, 65875, 65877, 65878, 65879, 65896,
            65906],
           dtype='int64', length=2725)

In [173]:
search_model = '쏘나타'

In [174]:
model_idx_list = df[df['car_name'].str.contains(search_model)].index

if len(model_idx_list) > 0:
    for idx in model_idx_list:
        p['car_model'][idx] = search_model

p[p['car_name'].str.contains(search_model)]

/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2878: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

,car_url,car_area,car_no,car_brand,nation,car_name,name_datailed,new_price,price,year,...,usage,change,insurance,sales_corp,sales_loca,lat,lng,options,options_count,new_col
44249,23004697,경기,16너4117,현대,국산,현대 YF쏘나타,LPi 프리미어,2133,320,2010,...,없음,1,있음,블루오토,경기 수원시,37.263332,127.028747,"['가죽시트', '하이패스룸밀러', '알루미늄휠']",3,쏘나타
44253,23004669,광주,47오9020,현대,국산,현대 쏘나타 더 브릴리언트,LPI 스마트,1814,490,2013,...,없음,1,있음,주식회사 한결모터스,광주광역시 서구,35.152140,126.890056,"['내비게이션', '주차감지센서', '열선시트', '전동접이사이드미러', '알루미늄휠']",5,쏘나타
44256,23004651,경기,46노0876,현대,국산,현대 LF쏘나타 하이브리드,2.0 HEV 모던,3173,1650,2016,...,없음,1,있음,(주)축석령중고차,경기 포천시,37.894827,127.200729,"['썬루프', '내비게이션', '스마트키', '하이패스룸밀러', '전동접이사이드미러...",6,쏘나타
44263,23004547,경북,13고3525,현대,국산,현대 YF쏘나타,LPi 프리미어,2193,680,2011,...,없음,3,있음,경일(구미),경북 구미시,36.119551,128.344469,[],0,쏘나타
44272,23004379,경기,26더2215,현대,국산,현대 쏘나타 뉴 라이즈,2.0 스마트 스페셜,2194,1690,2019,...,없음,2,있음,(주)구루마,경기 부천시,37.501442,126.766014,"['내비게이션', '스마트키', '오토라이트', '주차감지센서', '가죽시트', '...",8,쏘나타
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65877,11447722,광주,46부6538,현대,국산,현대 YF쏘나타,LPi 프리미어,1611,580,2010,...,없음,1,있음,(주)오성모터스,광주광역시 서구,35.152140,126.890056,[],0,쏘나타
65878,11440090,광주,50가2608,현대,국산,현대 LF쏘나타,LPI 프리미엄 일반형,1960,1490,2017,...,있음,1,없음,㈜보배모터스,광주 서구,35.152140,126.890056,"['내비게이션', '스마트키', '주차감지센서', '열선시트', '사이드커튼에어백'...",8,쏘나타
65879,11433516,광주,20노7547,현대,국산,현대 LF쏘나타,LPI 모던 일반형,1884,1470,2016,...,있음,1,없음,㈜보배모터스,광주 서구,35.152140,126.890056,"['내비게이션', '스마트키', '주차감지센서', '열선시트', '사이드커튼에어백'...",7,쏘나타
65896,11354576,광주,40부4517,현대,국산,현대 LF쏘나타,LPI 프리미엄 일반형,2138,1540,2016,...,있음,1,없음,㈜보배모터스,광주 서구,35.152140,126.890056,"['내비게이션', '스마트키', '주차감지센서', '열선시트', '사이드커튼에어백'...",8,쏘나타
65906,11270887,인천,08조2431,현대,국산,현대 쏘나타 뉴 라이즈,1.7 디젤 모던,2414,1980,2018,...,없음,0,없음,(주)에이엠지모터스,인천 서구,37.545000,126.676000,"['썬루프', '내비게이션', '스마트키']",3,쏘나타