In [27]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import matplotlib.pyplot as plt
from matplotlib import rc
%matplotlib inline
from matplotlib import font_manager
from tqdm import tqdm

font_name = font_manager.FontProperties(fname="HMFMMUEX.TTC").get_name()
rc('font', family=font_name)
plt.rcParams['axes.unicode_minus'] = False
pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv('preprocessed_total_0603.csv')

In [3]:
df.head(2)

,car_url,car_area,car_no,car_brand,nation,car_name,name_datailed,new_price,price,year,use,depreciation,mileage,fuel,forecast_min,forecast_max,car_type,car_cc,color,trans,loss,flood,usage,change,insurance,sales_corp,sales_loca,lat,lng,options,options_count
0,22274652,경기,29너6142,한국GM,국산,한국GM 쉐보레 올란도,LPG LS 일반형,2122,849,2013,103,60,131493,LPG,535,750,RV,0,인기색상,오토,없음,없음,없음,1,있음,주식회사 노빌리티 경기지점,경기 수원시,37.263332,127.028747,[],0
1,22274154,광주,156서1980,한국GM,국산,한국GM 더 뉴 트랙스,1.6 디젤 LT 기본형,1986,1450,2018,52,27,60000,디젤,1104,1533,SUV,1598,회색,오토,없음,없음,있음,2,없음,주식회사 즐거운모터스,광주 서구,35.152140,126.890056,"['주차감지센서', '가죽시트', '열선시트', '사이드커튼에어백', '전동접이사이...",7

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90802 entries, 0 to 90801
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   car_url        90802 non-null  int64
 1   car_area       90802 non-null  object
 2   car_no         90802 non-null  object
 3   car_brand      90802 non-null  object
 4   nation         90802 non-null  object
 5   car_name       90802 non-null  object
 6   name_datailed  90802 non-null  object
 7   new_price      90802 non-null  int64
 8   price          90802 non-null  int64
 9   year           90802 non-null  int64
 10  use            90802 non-null  int64
 11  depreciation   90802 non-null  int64
 12  mileage        90802 non-null  int64
 13  fuel           90802 non-null  object
 14  forecast_min   90802 non-null  int64
 15  forecast_max   90802 non-null  int64
 16  car_type       90802 non-null  object
 17  car_cc         90802 non-null  int64
 18  color          90802 non-null  object
 19  trans          90802 non-null  object
 20  loss           90802 non-null  object
 21  flood          90802 non-null  object
 22  usage          90802 non-null  object
 23  change         90802 non-null  int64
 24  insurance      90802 non-null  object
 25  sales_corp     90802 non-null  object
 26  sales_loca     90802 non-null  object
 27  lat            90802 non-null  float64
 28  lng            90802 non-null  float64
 29  options        90802 non-null  object
 30  options_count  90802 non-null  int64
dtypes: float64(2), int64(12), object(17)
memory usage: 21.5+ MB

# 여기서 부터 모델명으로 통합전처리

In [5]:
df.insert(5,'car_model','')

In [6]:
df.head(2)

,car_url,car_area,car_no,car_brand,nation,car_model,car_name,name_datailed,new_price,price,year,use,depreciation,mileage,fuel,forecast_min,forecast_max,car_type,car_cc,color,trans,loss,flood,usage,change,insurance,sales_corp,sales_loca,lat,lng,options,options_count
0,22274652,경기,29너6142,한국GM,국산,,한국GM 쉐보레 올란도,LPG LS 일반형,2122,849,2013,103,60,131493,LPG,535,750,RV,0,인기색상,오토,없음,없음,없음,1,있음,주식회사 노빌리티 경기지점,경기 수원시,37.263332,127.028747,[],0
1,22274154,광주,156서1980,한국GM,국산,,한국GM 더 뉴 트랙스,1.6 디젤 LT 기본형,1986,1450,2018,52,27,60000,디젤,1104,1533,SUV,1598,회색,오토,없음,없음,있음,2,없음,주식회사 즐거운모터스,광주 서구,35.152140,126.890056,"['주차감지센서', '가죽시트', '열선시트', '사이드커튼에어백', '전동접이사이...",7

In [15]:
youtube_df = pd.read_csv('youtube_total_0604.csv')
youtube_df.head(3)

,car_brand,car_model,comments,likes
0,BMW,1시리즈,"주제선정 좋아요. 더운 여름 잘 지내세요. 비싼차, 싼차, 슈퍼카, 경차 가리지 않...",3
1,BMW,1시리즈,주차장 시승평 잘봤네요ㅋ 그냥 외관이랑 실내평만 보면 편안할듯ㅋㅋ 매력적인 차네요 ...,3
2,BMW,1시리즈,차 가격도 싸고 디자인도 예쁘고 엄청 좋다,5

In [16]:
df[(df['car_brand'].str.contains('현대'))&(df['car_name'].str.contains('쏘나타'))].index

Int64Index([44249, 44253, 44256, 44263, 44272, 44281, 44284, 44288, 44290,
            44303,
            ...
            65844, 65862, 65869, 65870, 65875, 65877, 65878, 65879, 65896,
            65906],
           dtype='int64', length=2725)

In [7]:
df[df['car_name'].str.contains('쏘나타')].index

Int64Index([44249, 44253, 44256, 44263, 44272, 44281, 44284, 44288, 44290,
            44303,
            ...
            65844, 65862, 65869, 65870, 65875, 65877, 65878, 65879, 65896,
            65906],
           dtype='int64', length=2725)

In [ ]:
# 1)브랜드명이 x이면서, 2) 모델명이 y인 경우의 DataFrame의 index를 구하시오.

In [17]:
youtube_df['car_brand'].unique()

array(['BMW', '기아', '기타', '닛산', '다이하쓰', '도요타', '랜드로버', '롤스로이스', '르노코리아',
       '마쯔다', '미쯔비시', '벤츠', '볼보', '사브', '시트로엥', '쌍용', '아우디', '재규어',
       '크라이슬러', '포드', '포르쉐', '폭스바겐', '푸조', '피아트', '한국GM', '현대', '혼다'],
      dtype=object)

In [18]:
df['car_brand'].unique()

array(['한국GM', '르노삼성', '르노코리아', '쌍용', '폭스바겐', '닛산', '지프', '미니', '푸조',
       '도요타', '마세라티', '혼다', '캐딜락', '렉서스', '랜드로버', '포르쉐', '포드', '재규어',
       '인피니티', '볼보', '링컨', '크라이슬러', '쉐보레', '시트로엥', '벤틀리', '피아트', '애스턴마틴',
       '닷지', '페라리', '테슬라', '제네시스', 'BMW', '다이하쓰', '로버', '사브', '벤츠', 'MAN',
       '아우디', '허머', '스즈키', '롤스로이스', '맥라렌', '어큐라', '스바루', '동풍자동차', '스마트',
       '미쯔비시', '람보르기니', 'GMC', '마쯔다', '중한자동차', '이베코', '마이바흐', '포톤',
       '선롱버스', '현대', '기아'], dtype=object)

---
### 댓글에 없는 브랜드가 많아서 우선 댓글 기준으로 모델명 정리
---

In [23]:
brand_list = youtube_df['car_brand'].unique()
model_list = youtube_df['car_model'].unique()

In [28]:
for brand in tqdm(brand_list):
    search_brand = brand
    for model in model_list:
        search_model = model
        
        model_idx_list = df[(df['car_brand'].str.contains(search_brand))&(df['car_name'].str.contains(search_model))].index

        if len(model_idx_list) > 0:
            for idx in model_idx_list:
                df['car_model'][idx] = search_model

df[df['car_name'].str.contains(search_model)]

  0%|          | 0/27 [00:00<?, ?it/s]/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/strings.py:2001: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
100%|██████████| 27/27 [10:11<00:00, 22.66s/it]

,car_url,car_area,car_no,car_brand,nation,car_model,car_name,name_datailed,new_price,price,year,use,depreciation,mileage,fuel,forecast_min,forecast_max,car_type,car_cc,color,trans,loss,flood,usage,change,insurance,sales_corp,sales_loca,lat,lng,options,options_count
11671,22986471,경기,20보4464,혼다,수입,파일럿,혼다 파일럿(3세대),3.5 V6 4WD 기본형,5250,2730,2017,55,48,77119,가솔린,2422,2716,RV,0,검정색,오토,없음,없음,없음,1,있음,주식회사 오토룩,경기 수원시,37.263332,127.028747,"['썬루프', '내비게이션', '스마트키', '오토라이트', '주차감지센서', '가...",8
13231,22973406,경기,20보0227,혼다,수입,파일럿,혼다 파일럿(3세대),3.5 V6 4WD 기본형,5180,2590,2016,63,50,72000,가솔린,2183,2478,RV,0,은색,오토,없음,없음,없음,3,없음,주식회사 설레임오토모티브,경기 수원시,37.263332,127.028747,"['썬루프', '스마트키', '가죽시트', '크루즈컨트롤', '알루미늄휠']",5
13818,22970739,경기,42구0530,혼다,수입,파일럿,혼다 파일럿(3세대),3.5 V6 4WD 기본형,5236,1990,2016,71,62,162000,가솔린,1438,1732,RV,0,흰색,오토,없음,없음,없음,4,없음,(주)왕카,경기 수원시,37.263332,127.028747,"['썬루프', '스마트키', '가죽시트', '하이패스룸밀러', '전동접이사이드미러'...",7
24200,22847345,경기,02버2583,혼다,수입,파일럿,혼다 파일럿(3세대),3.5 V6 4WD 기본형,4963,2730,2017,54,45,63375,가솔린,2707,2998,RV,3471,검정색,오토,없음,없음,없음,1,있음,주식회사 카프랜즈,경기 부천시,37.501442,126.766014,"['썬루프', '내비게이션', '스마트키', '오토라이트', '주차감지센서', '가...",8
24429,22844296,경기,316어2224,혼다,수입,파일럿,혼다 파일럿(3세대),3.5 V6 4WD Elite,4447,4270,2019,29,4,39238,가솔린,3889,4213,RV,3471,검정,오토,없음,없음,없음,1,있음,(주)오토앤오토,경기 김포시,37.615461,126.715789,"['오토라이트', '주차감지센서', '가죽시트', '열선시트', '사이드커튼에어백'...",8
28139,22783347,경기,362모5513,혼다,수입,파일럿,혼다 파일럿(3세대),3.5 V6 4WD Elite,5569,4400,2019,38,21,35699,가솔린,3584,3874,RV,3471,회색,오토,없음,없음,있음,1,없음,카메이트,경기 수원시,37.263332,127.028747,"['썬루프', '내비게이션', '스마트키', '오토라이트', '주차감지센서', '가...",8
29606,22749073,경기,14노0238,혼다,수입,파일럿,혼다 파일럿(3세대),3.5 V6 4WD LX,5208,2500,2016,66,52,95195,가솔린,2478,2799,RV,3471,검정색,오토,없음,없음,없음,4,있음,스마일자동차,경기 부천시,37.501442,126.766014,"['오토라이트', '주차감지센서', '가죽시트', '열선시트', '사이드커튼에어백'...",8
29651,22747090,경기,01라8439,혼다,수입,파일럿,혼다 파일럿(3세대),3.5 V6 4WD Elite,5328,4050,2019,34,24,38652,가솔린,3993,4317,RV,3471,회색,오토,없음,없음,없음,3,없음,주시회사 다온모터스,경기 수원시,37.263332,127.028747,"['썬루프', '내비게이션', '스마트키', '오토라이트', '주차감지센서', '가...",8
35602,22549059,인천,58루4724,혼다,수입,파일럿,혼다 파일럿,3.5 V6 EX 4WD,4647,1580,2013,107,66,127137,가솔린,1318,1588,RV,3471,검정,오토,없음,없음,없음,3,있음,(주)유카 인천지점,인천 서구,37.545000,126.676000,['내비게이션'],1
35685,22543895,경기,63가4535,혼다,수입,파일럿,혼다 파일럿(3세대),3.5 V6 4WD 기본형,5035,2870,2018,49,43,61498,가솔린,2376,3340,RV,0,인기색상,오토,없음,없음,없음,3,있음,(주)알차이노베이션,경기 안산시,37.321715,126.830860,"['오토라이트', '주차감지센서', '가죽시트', '열선시트', '사이드커튼에어백'...",8
41122,21731216,부산,31가3767,혼다,수입,파일럿,혼다 파일럿(3세대),3.5 V6 4WD 기본형,4803,2930,2018,46,39,61803,가솔린,2171,3091,RV,3471,회색,오토,없음,없음,없음,1,없음,정모터스,부산 기장군,35.244600,129.223000,"['오토라이트', '주차감지센서', '가죽시트', '열선시트', '사이드커튼에어백'...",8

In [33]:
# 중고차 DataFrame에서 'car_model' 빈 부분 찾기

df[df['car_model'] =='']['car_name'].unique()

array(['한국GM 더 뉴 트랙스', '한국GM 더 뉴 스파크', '한국GM 올 뉴 크루즈', '한국GM 올 뉴 말리부',
       '한국GM 더 넥스트 스파크', '한국GM 어메이징 뉴 크루즈', '한국GM 리얼 뉴 콜로라도',
       '한국GM 더 뉴 말리부', '한국GM 임팔라', '한국GM 콜로라도', '한국GM 더 넥스트 스파크 밴',
       '한국GM 올 뉴 카마로', '르노삼성 ALL New SM7 노바', '르노삼성 SM6', '르노삼성 QM3',
       '르노삼성 SM5 뉴임프레션', '르노삼성 SM7 뉴아트', '르노삼성 뉴SM3', '르노삼성 뉴SM5 플래티넘',
       '르노삼성 QM5', '르노삼성 클리오', '르노삼성 뉴SM5', '르노삼성 SM3 네오',
       '르노삼성 뉴SM5(신형)', '르노삼성 QM5 NEO', '르노삼성 All New SM7', '르노삼성 뉴QM5',
       '르노삼성 SM5 노바', '르노삼성 The New SM6', '르노삼성 QM6', '르노삼성 뉴 QM6',
       '르노삼성 SM5', '르노삼성 SM7', '르노삼성 New QM3', '르노삼성 XM3', '르노삼성 SM3',
       '르노삼성 캡처', '르노삼성 더 뉴 QM6', '르노삼성 마스터 밴', '르노삼성 뉴 마스터 버스',
       '르노삼성 SM3 뉴제너레이션', '르노삼성 SM3 Z.E.', '르노삼성 트위지', '르노삼성 조에',
       '르노삼성 마스터 버스', '쌍용 렉카', '지프 체로키', '미니 쿠퍼', '미니 컨트리맨', '마세라티 뉴 기블리',
       '미니 뉴 클럽맨', '미니 쿠퍼 3도어', '캐딜락 ATS', '렉서스 RX', '지프 랭글러', '렉서스 뉴 ES',
       '미니 쿠퍼 5도어', '지프 그랜드 체로키', '캐딜락 CT6', '지프 레니게이드', '미니 쿠퍼 컨버터블',
       '렉서스 NX', '인피니티 G37', '렉서스 LS', '마세라티 콰트로포르테', '인피니티 Q50',
       '링컨 노틸러스', '인피니티 Q70', '렉서스 ES', '인피니티 G25', '캐딜락 CT5', '쉐보레 콜로라도',
       '링컨 MKS', '벤틀리 플라잉스퍼 1세대', '지프 뉴 컴패스', '마세라티 기블리', '링컨 뉴 MKZ',
       '지프 글래디에이터', '링컨 컨티넨탈 10세대', '캐딜락 XT5', '인피니티 EX35', '지프 랭글러 (JL)',
       '미니 쿠퍼 로드스터', '링컨 MKC', '렉서스 뉴 LS', '인피니티 M35', '애스턴마틴 밴티지',
       '캐딜락 CTS 3세대', '렉서스 CT', '미니 클럽맨', '닷지 챌린저', '페라리 488 스파이더',
       '테슬라 Model 3', '렉서스 뉴 RX', '한국GM 신형 캡티바', '한국GM 어메이징 뉴 크루즈5',
       '미니 뉴 컨트리맨 (F60)', '렉서스 RC', '제네시스 G80(DH)', '렉서스 GS',
       '제네시스 G80(RG3)', '제네시스 EQ900', '제네시스 G70', '지프 컴패스', '인피니티 M37',
       '제네시스 G90', '제네시스 G70 SPORT', '렉서스 뉴 제너레이션 ES', '제네시스 G80 SPORT',
       '제네시스 GV80', '미니 페이스맨', '인피니티 QX70', '한국GM 더 뉴 스파크 밴', '닷지 램 픽업',
       '링컨 뉴 MKS', 'BMW 그란투리스모', '캐딜락 ESCALADE(4세대)', '미니 뉴 컨버터블',
       '인피니티 QX30', '도요타 RAV4', '렉서스 뉴 IS', '제네시스 더 뉴 G70', '로버 미니',
       '링컨 MKX 2세대', '마세라티 르반떼', '인피니티 G35', '쉐보레 익스프레스밴', '한국GM 트래버스',
       '벤츠 뉴 E클래스', '벤츠 GLE', '벤츠 E클래스 (W213)', '벤츠 뉴 C클래스', '벤츠 CLA클래스',
       '벤츠 더 뉴 C클래스', '벤츠 뉴 S클래스', 'MAN 트럭', '벤츠 CLA클래스(C118)',
       '벤츠 CLS클래스(W218)', '벤츠 CLS클래스(W219)', '지프 체로키(KL)', '벤츠 뉴 M클래스',
       '벤츠 A클래스(W177)', '벤츠 GLE (V167)', '한국GM 이쿼녹스', '렉서스 IS',
       '벤츠 CLS클래스(C257)', '벤츠 SLC클래스 (R172)', '벤츠 C클래스', '인피니티 Q30',
       '벤츠 B클래스 W246', '벤츠 CLK클래스', '링컨 에비에이터 2세대(U611)', '벤츠 A클래스',
       '벤츠 V클래스', '벤츠 E클래스', '벤츠 E클래스 (C238)', '제네시스 GV70', '허머 H3',
       '스즈키 허슬러', '지프 올뉴 컴패스', '링컨 뉴 MKX', '벤츠 GLA H247',
       '캐딜락 ESCALADE(1~3세대)', '벤츠 S클래스', '캐딜락 올 뉴 SRX', '벤츠 S클래스 W223',
       '벤츠 뉴 SLK클래스', '벤츠 GLS', '벤츠 B클래스', '벤츠 GLK클래스', '벤츠 M클래스',
       '페라리 F430', '벤틀리 벤테이가', '벤츠 G클래스', '테슬라 Model X', '쉐보레 서버밴',
       '링컨 타운카', '링컨 코세어', '인피니티 QX60', '맥라렌 720S', '렉서스 UX',
       '벤틀리 컨티넨탈 플라잉스퍼', '벤츠 스마트', '어큐라 MDX', '닷지 다코타',
       '벤틀리 뉴 컨티넨탈 플라잉스퍼', '도요타 뉴 RAV4', '제네시스 더 뉴 G70 SPORT', '캐딜락 XT6',
       '렉서스 LS 5세대', '인피니티 QX50', '크라이슬러 그랜드보이저', '인피니티 Q60', '인피니티 JX35',
       '미니 쿠페', '스바루 포레스터', '캐딜락 CTS 2세대', '벤츠 뉴 CL클래스', '인피니티 올 뉴 FX',
       '인피니티 EX30d', '마세라티 그란투리스모', '포르쉐 Taycan', '캐딜락 CT4',
       '벤틀리 뉴 컨티넨탈 GT', '동풍자동차 ix5', '벤틀리 컨티넨탈-GT', '벤츠 SLK클래스',
       '인피니티 QX50 2세대', '렉서스 뉴 GS', '한국GM 더 뉴 아베오', '한국GM 프리마', '링컨 MKX',
       '캐딜락 드빌', '벤틀리 플라잉스퍼 2세대', '스마트 포투 쿠페', '벤틀리 플라잉스퍼 3세대',
       '한국GM 레스타', '캐딜락 CTS-V', '인피니티 M45', '지프 그랜드 체로키(WL)', '벤츠 SL클래스',
       '링컨 MKZ', '렉서스 LC', '쉐보레 카마로', '벤츠 GL클래스', '캐딜락 ESCALADE(5세대)',
       '인피니티 FX35', '스바루 레거시', '마세라티 그란카브리오', '스마트 포투 카브리오',
       '람보르기니 아벤타도르', '쉐보레 익스플로러밴', 'GMC 시에라', '인피니티 M30d', '허머 H2',
       '맥라렌 650S', '링컨 네비게이터 4세대(U554)', '벤츠 뉴 SL클래스', '마세라티 스파이더',
       '미니 쿠퍼 S 로드스터', 'GMC 사바나밴', '중한자동차 KENBO 600', '닷지 캘리버',
       '한국GM 더 뉴 카마로', '인피니티 뉴 FX30d', '제네시스 ELECTRIFIED G80', '벤츠 벤츠',
       '스즈키 스위프트', '스즈키 알토라팡', '도요타 SCION', '람보르기니 가야르도', '인피니티 QX80',
       '캐딜락 CTS 1세대', '스바루 아웃백', '캐딜락 리무진', '캐딜락 DTS', '인피니티 뉴 FX35',
       '도요타 FJ크루저', '캐딜락 STS', '인피니티 Q45', '마쯔다 RX시리즈', '애스턴마틴 라피드',
       '애스턴마틴 DB9', '이베코 기타', '쉐보레 이퀴녹스', '캐딜락 ESCALADE', '벤틀리 뮬산',
       '캐딜락 ALL NEW ESCALADE', '람보르기니 우라칸', '닷지 듀랑고', '캐딜락 SRX',
       '애스턴마틴 뱅퀴시 S', '페라리 캘리포니아', '포드 파이브헌드레드', '마세라티 쿠페', '마쯔다 MX-5',
       '캐딜락 ATS-V', '애스턴마틴 DB11', '맥라렌 675LT', '스바루 임프레자 WRX', '맥라렌 570S',
       '렉서스 SC', '마이바흐 57', '지프 커맨더', '벤츠 R클래스', '미쯔비시 렌서에볼루션', '링컨 LS',
       '벤츠 GLC', '인피니티 QX', '벤츠 뉴 CLS클래스', '페라리 FF', '캐딜락 BLS',
       '마이바흐 62s', '한국GM BS', '르노삼성 뉴 마스터 밴', '포톤 툰랜드', '동풍자동차 밴',
       '한국GM 노부스', '중한자동차 CK 미니 밴', '동풍자동차 소형트럭', '한국GM BH',
       '중한자동차 CK 미니 트럭', '선롱버스 DUEGO', '테슬라 모델 S', '렉서스 뉴 CT',
       '링컨 올 뉴 MKZ', '현대 베뉴', '현대 e-카운티', '현대 현대버스', '현대 뉴카운티',
       '현대 에어로타운', '현대 e-에어로타운 (04년~', '현대 카운티', '현대 유니버스', '기아 라이노',
       '기아 뉴그랜버드'], dtype=object)

## 1. 한국GM에 모델명에 '쉐보레 '삭제해주고 다시 돌리기

In [44]:
youtube_df[youtube_df['car_brand'].str.contains('한국GM')]['car_model'].unique()

array(['G2X', '다마스', '대우버스', '라노스', '라보', '라세티', '레조', '르망', '마티즈',
       '매그너스', '베리타스', '브로엄', '쉐보레 말리부', '쉐보레 볼트', '쉐보레 스파크', '쉐보레 아베오',
       '쉐보레 올란도', '쉐보레 이쿼녹스', '쉐보레 임팔라', '쉐보레 카마로', '쉐보레 캡티바', '쉐보레 콜로라도',
       '쉐보레 콜벳', '쉐보레 크루즈', '쉐보레 트래버스', '쉐보레 트랙스', '쉐보레 트레일블레이저', '스테이츠맨',
       '아카디아', '알페온', '윈스톰', '젠트라', '토스카', '트럭(4.5톤이상)', '티코', '프린스'],
      dtype=object)

In [51]:
search_brand = '한국GM'
model_list2 = youtube_df[youtube_df['car_brand'].str.contains(search_brand)]['car_model'].unique()

for model in model_list2:
    search_model = model.replace('쉐보레 ','')

    model_idx_list = df[(df['car_brand'].str.contains(search_brand))&(df['car_name'].str.contains(search_model))].index

    if len(model_idx_list) > 0:
        for idx in model_idx_list:
            df['car_model'][idx] = search_model

df[df['car_name'].str.contains(search_model)]

/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/strings.py:2001: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

Empty DataFrame
Columns: [car_url, car_area, car_no, car_brand, nation, car_model, car_name, name_datailed, new_price, price, year, use, depreciation, mileage, fuel, forecast_min, forecast_max, car_type, car_cc, color, trans, loss, flood, usage, change, insurance, sales_corp, sales_loca, lat, lng, options, options_count]
Index: []

In [52]:
# 중고차 DataFrame에서 'car_model' 빈 부분 찾기

df[df['car_model'] =='']['car_name'].unique()

array(['르노삼성 ALL New SM7 노바', '르노삼성 SM6', '르노삼성 QM3', '르노삼성 SM5 뉴임프레션',
       '르노삼성 SM7 뉴아트', '르노삼성 뉴SM3', '르노삼성 뉴SM5 플래티넘', '르노삼성 QM5',
       '르노삼성 클리오', '르노삼성 뉴SM5', '르노삼성 SM3 네오', '르노삼성 뉴SM5(신형)',
       '르노삼성 QM5 NEO', '르노삼성 All New SM7', '르노삼성 뉴QM5', '르노삼성 SM5 노바',
       '르노삼성 The New SM6', '르노삼성 QM6', '르노삼성 뉴 QM6', '르노삼성 SM5',
       '르노삼성 SM7', '르노삼성 New QM3', '르노삼성 XM3', '르노삼성 SM3', '르노삼성 캡처',
       '르노삼성 더 뉴 QM6', '르노삼성 마스터 밴', '르노삼성 뉴 마스터 버스', '르노삼성 SM3 뉴제너레이션',
       '르노삼성 SM3 Z.E.', '르노삼성 트위지', '르노삼성 조에', '르노삼성 마스터 버스', '쌍용 렉카',
       '지프 체로키', '미니 쿠퍼', '미니 컨트리맨', '마세라티 뉴 기블리', '미니 뉴 클럽맨',
       '미니 쿠퍼 3도어', '캐딜락 ATS', '렉서스 RX', '지프 랭글러', '렉서스 뉴 ES',
       '미니 쿠퍼 5도어', '지프 그랜드 체로키', '캐딜락 CT6', '지프 레니게이드', '미니 쿠퍼 컨버터블',
       '렉서스 NX', '인피니티 G37', '렉서스 LS', '마세라티 콰트로포르테', '인피니티 Q50',
       '링컨 노틸러스', '인피니티 Q70', '렉서스 ES', '인피니티 G25', '캐딜락 CT5', '쉐보레 콜로라도',
       '링컨 MKS', '벤틀리 플라잉스퍼 1세대', '지프 뉴 컴패스', '마세라티 기블리', '링컨 뉴 MKZ',
       '지프 글래디에이터', '링컨 컨티넨탈 10세대', '캐딜락 XT5', '인피니티 EX35', '지프 랭글러 (JL)',
       '미니 쿠퍼 로드스터', '링컨 MKC', '렉서스 뉴 LS', '인피니티 M35', '애스턴마틴 밴티지',
       '캐딜락 CTS 3세대', '렉서스 CT', '미니 클럽맨', '닷지 챌린저', '페라리 488 스파이더',
       '테슬라 Model 3', '렉서스 뉴 RX', '미니 뉴 컨트리맨 (F60)', '렉서스 RC',
       '제네시스 G80(DH)', '렉서스 GS', '제네시스 G80(RG3)', '제네시스 EQ900',
       '제네시스 G70', '지프 컴패스', '인피니티 M37', '제네시스 G90', '제네시스 G70 SPORT',
       '렉서스 뉴 제너레이션 ES', '제네시스 G80 SPORT', '제네시스 GV80', '미니 페이스맨',
       '인피니티 QX70', '닷지 램 픽업', '링컨 뉴 MKS', 'BMW 그란투리스모',
       '캐딜락 ESCALADE(4세대)', '미니 뉴 컨버터블', '인피니티 QX30', '도요타 RAV4',
       '렉서스 뉴 IS', '제네시스 더 뉴 G70', '로버 미니', '링컨 MKX 2세대', '마세라티 르반떼',
       '인피니티 G35', '쉐보레 익스프레스밴', '벤츠 뉴 E클래스', '벤츠 GLE', '벤츠 E클래스 (W213)',
       '벤츠 뉴 C클래스', '벤츠 CLA클래스', '벤츠 더 뉴 C클래스', '벤츠 뉴 S클래스', 'MAN 트럭',
       '벤츠 CLA클래스(C118)', '벤츠 CLS클래스(W218)', '벤츠 CLS클래스(W219)',
       '지프 체로키(KL)', '벤츠 뉴 M클래스', '벤츠 A클래스(W177)', '벤츠 GLE (V167)',
       '렉서스 IS', '벤츠 CLS클래스(C257)', '벤츠 SLC클래스 (R172)', '벤츠 C클래스',
       '인피니티 Q30', '벤츠 B클래스 W246', '벤츠 CLK클래스', '링컨 에비에이터 2세대(U611)',
       '벤츠 A클래스', '벤츠 V클래스', '벤츠 E클래스', '벤츠 E클래스 (C238)', '제네시스 GV70',
       '허머 H3', '스즈키 허슬러', '지프 올뉴 컴패스', '링컨 뉴 MKX', '벤츠 GLA H247',
       '캐딜락 ESCALADE(1~3세대)', '벤츠 S클래스', '캐딜락 올 뉴 SRX', '벤츠 S클래스 W223',
       '벤츠 뉴 SLK클래스', '벤츠 GLS', '벤츠 B클래스', '벤츠 GLK클래스', '벤츠 M클래스',
       '페라리 F430', '벤틀리 벤테이가', '벤츠 G클래스', '테슬라 Model X', '쉐보레 서버밴',
       '링컨 타운카', '링컨 코세어', '인피니티 QX60', '맥라렌 720S', '렉서스 UX',
       '벤틀리 컨티넨탈 플라잉스퍼', '벤츠 스마트', '어큐라 MDX', '닷지 다코타',
       '벤틀리 뉴 컨티넨탈 플라잉스퍼', '도요타 뉴 RAV4', '제네시스 더 뉴 G70 SPORT', '캐딜락 XT6',
       '렉서스 LS 5세대', '인피니티 QX50', '크라이슬러 그랜드보이저', '인피니티 Q60', '인피니티 JX35',
       '미니 쿠페', '스바루 포레스터', '캐딜락 CTS 2세대', '벤츠 뉴 CL클래스', '인피니티 올 뉴 FX',
       '인피니티 EX30d', '마세라티 그란투리스모', '포르쉐 Taycan', '캐딜락 CT4',
       '벤틀리 뉴 컨티넨탈 GT', '동풍자동차 ix5', '벤틀리 컨티넨탈-GT', '벤츠 SLK클래스',
       '인피니티 QX50 2세대', '렉서스 뉴 GS', '한국GM 프리마', '링컨 MKX', '캐딜락 드빌',
       '벤틀리 플라잉스퍼 2세대', '스마트 포투 쿠페', '벤틀리 플라잉스퍼 3세대', '한국GM 레스타',
       '캐딜락 CTS-V', '인피니티 M45', '지프 그랜드 체로키(WL)', '벤츠 SL클래스', '링컨 MKZ',
       '렉서스 LC', '쉐보레 카마로', '벤츠 GL클래스', '캐딜락 ESCALADE(5세대)', '인피니티 FX35',
       '스바루 레거시', '마세라티 그란카브리오', '스마트 포투 카브리오', '람보르기니 아벤타도르',
       '쉐보레 익스플로러밴', 'GMC 시에라', '인피니티 M30d', '허머 H2', '맥라렌 650S',
       '링컨 네비게이터 4세대(U554)', '벤츠 뉴 SL클래스', '마세라티 스파이더', '미니 쿠퍼 S 로드스터',
       'GMC 사바나밴', '중한자동차 KENBO 600', '닷지 캘리버', '인피니티 뉴 FX30d',
       '제네시스 ELECTRIFIED G80', '벤츠 벤츠', '스즈키 스위프트', '스즈키 알토라팡',
       '도요타 SCION', '람보르기니 가야르도', '인피니티 QX80', '캐딜락 CTS 1세대', '스바루 아웃백',
       '캐딜락 리무진', '캐딜락 DTS', '인피니티 뉴 FX35', '도요타 FJ크루저', '캐딜락 STS',
       '인피니티 Q45', '마쯔다 RX시리즈', '애스턴마틴 라피드', '애스턴마틴 DB9', '이베코 기타',
       '쉐보레 이퀴녹스', '캐딜락 ESCALADE', '벤틀리 뮬산', '캐딜락 ALL NEW ESCALADE',
       '람보르기니 우라칸', '닷지 듀랑고', '캐딜락 SRX', '애스턴마틴 뱅퀴시 S', '페라리 캘리포니아',
       '포드 파이브헌드레드', '마세라티 쿠페', '마쯔다 MX-5', '캐딜락 ATS-V', '애스턴마틴 DB11',
       '맥라렌 675LT', '스바루 임프레자 WRX', '맥라렌 570S', '렉서스 SC', '마이바흐 57',
       '지프 커맨더', '벤츠 R클래스', '미쯔비시 렌서에볼루션', '링컨 LS', '벤츠 GLC', '인피니티 QX',
       '벤츠 뉴 CLS클래스', '페라리 FF', '캐딜락 BLS', '마이바흐 62s', '한국GM BS',
       '르노삼성 뉴 마스터 밴', '포톤 툰랜드', '동풍자동차 밴', '한국GM 노부스', '중한자동차 CK 미니 밴',
       '동풍자동차 소형트럭', '한국GM BH', '중한자동차 CK 미니 트럭', '선롱버스 DUEGO',
       '테슬라 모델 S', '렉서스 뉴 CT', '링컨 올 뉴 MKZ', '현대 베뉴', '현대 e-카운티',
       '현대 현대버스', '현대 뉴카운티', '현대 에어로타운', '현대 e-에어로타운 (04년~', '현대 카운티',
       '현대 유니버스', '기아 라이노', '기아 뉴그랜버드'], dtype=object)

## 2. 르노삼성 >> 르노코리아 처리해주기

In [38]:
youtube_df[youtube_df['car_brand'].str.contains('르노')]

,car_brand,car_model,comments,likes
79490,르노코리아,QM3,오토뷰는 차량에 필요한 정보를 정리해서 볼 수 있어서 좋다. 정리가 깔끔하다.,2
79491,르노코리아,QM3,업무용으로 qm3를 타는데요 갠적으로는 나름 쫀쫀한 하체 감각이나 핸들링이 괜찮게 ...,5
79492,르노코리아,QM3,얘는 진짜 유럽에서 잘나갈 차다... 그리고 우리나라에서도 정말 끌기 좋은차 가격 ...,12
79493,르노코리아,QM3,잘봤습니다. 요즘은 솔직히 이차가 가진 특정한 매력 외에는 구매추천하기가 쉽지 않은...,3
79494,르노코리아,QM3,연비만큼은 최고네요진짜,20
...,...,...,...,...
93277,르노코리아,트위지,이거 테스트용이러고 해야하나 문짝 비닐하우스 비닐 떼어다가 만든것처럼 붙혀놓고 a4...,1
93278,르노코리아,트위지,이거 봐도 대가리 깨져도 트위지 타는사람 있더라 차라리 중고로 소형차로 사지,1
93279,르노코리아,트위지,1500 이면 모닝 사겟다 ㅎㅎㅎ,1
93280,르노코리아,트위지,일단 다필요없고 타기너무 쪽팔린듯 ㅋㅋㅋ,1
93281,르노코리아,트위지,ㅋㅋㅋㅋㅋ 죄송한데 왜케 웃기지요... ㅋㅋ,2

In [53]:
# 르노코리아 = 르노삼성

search_brand = '르노'
model_list2 = youtube_df[youtube_df['car_brand'].str.contains(search_brand)]['car_model'].unique()

for model in model_list2:
    search_model = model.replace('쉐보레 ','')

    model_idx_list = df[(df['car_brand'].str.contains(search_brand))&(df['car_name'].str.contains(search_model))].index

    if len(model_idx_list) > 0:
        for idx in model_idx_list:
            df['car_model'][idx] = search_model

df[df['car_name'].str.contains(search_model)]

/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

,car_url,car_area,car_no,car_brand,nation,car_model,car_name,name_datailed,new_price,price,year,use,depreciation,mileage,fuel,forecast_min,forecast_max,car_type,car_cc,color,trans,loss,flood,usage,change,insurance,sales_corp,sales_loca,lat,lng,options,options_count
2327,22977390,경기,41보6549,르노코리아,국산,트위지,르노코리아 트위지,EV 인텐스,1403,365,2018,47,74,5207,전기,796,1131,경차,0,주황색,오토,없음,없음,있음,1,없음,차왕모터스,경기 수원시,37.263332,127.028747,"['주차감지센서', '알루미늄휠']",2
2400,22958100,서울,66가5927,르노코리아,국산,트위지,르노코리아 트위지,EV 카고,1480,370,2019,37,75,4400,전기,700,1036,경차,0,빨강(주홍),오토,없음,없음,없음,2,없음,에스에스카,서울 강서구,37.550900,126.849700,['주차감지센서'],1
2409,22973127,경기,68보9268,르노코리아,국산,트위지,르노코리아 트위지,EV 인텐스,1207,459,2020,22,62,1918,전기,1112,1449,경차,0,흰색,오토,없음,없음,없음,6,없음,벧엘자동차2,경기 수원시,37.263332,127.028747,"['주차감지센서', '알루미늄휠']",2
2410,22973120,경기,32소2332,르노코리아,국산,트위지,르노코리아 트위지,EV 인텐스,1495,359,2018,51,76,15472,전기,805,1139,경차,0,흰색,오토,없음,없음,없음,1,없음,벧엘자동차2,경기 수원시,37.263332,127.028747,['주차감지센서'],1
2411,22973116,경기,50보1788,르노코리아,국산,트위지,르노코리아 트위지,EV 인텐스,1140,399,2019,34,65,13755,전기,567,907,경차,0,흰색,오토,없음,없음,없음,5,없음,벧엘자동차2,경기 수원시,37.263332,127.028747,['주차감지센서'],1
2412,22973110,경기,45더8235,르노코리아,국산,트위지,르노코리아 트위지,EV 인텐스,1375,399,2019,43,71,5631,전기,871,1209,경차,0,흰색,오토,없음,없음,있음,4,없음,벧엘자동차2,경기 수원시,37.263332,127.028747,"['주차감지센서', '알루미늄휠']",2
2413,22973106,경기,37너1310,르노코리아,국산,트위지,르노코리아 트위지,EV 인텐스,1534,399,2018,46,74,4235,전기,875,1208,경차,0,흰색,오토,없음,없음,없음,2,있음,벧엘자동차2,경기 수원시,37.263332,127.028747,['주차감지센서'],1
2466,22970817,경기,09구7068,르노코리아,국산,트위지,르노코리아 트위지,EV 인텐스,1458,350,2018,43,76,3920,전기,739,1076,경차,0,주황색,오토,없음,없음,있음,1,없음,(주)왕카,경기 수원시,37.263332,127.028747,['주차감지센서'],1
2829,22939182,경기,50보4627,르노삼성,국산,트위지,르노삼성 트위지,EV 라이프,1166,420,2020,22,64,1156,전기,1166,1502,경차,0,인기색상,오토,없음,없음,없음,4,없음,주식회사자동차마을,경기 수원시,37.263332,127.028747,['주차감지센서'],1
2870,22934428,경기,21우2427,르노삼성,국산,트위지,르노삼성 트위지,EV 카고,1052,400,2019,33,62,409,전기,789,1125,경차,0,인기색상,오토,없음,없음,없음,2,없음,케이에스자동차,경기 수원시,37.263332,127.028747,['주차감지센서'],1
2904,22848771,경기,27소6938,르노삼성,국산,트위지,르노삼성 트위지,EV 라이프,1344,390,2019,37,71,6948,전기,112,400,경차,0,흰색,오토,없음,없음,없음,2,없음,차왕모터스,경기 수원시,37.263332,127.028747,"['썬루프', '내비게이션', '스마트키', '주차감지센서', '가죽시트', '하이...",8
2905,22856606,경기,64보5201,르노삼성,국산,트위지,르노삼성 트위지,EV 인텐스,1535,430,2018,48,72,5328,전기,438,952,경차,0,검정색,오토,없음,없음,없음,2,없음,차왕모터스,경기 수원시,37.263332,127.028747,"['주차감지센서', '알루미늄휠']",2
2917,22929388,경기,39거1228,르노삼성,국산,트위지,르노삼성 트위지,EV 인텐스,1500,420,2018,52,72,919,전기,858,1192,경차,0,흰색,오토,없음,없음,없음,2,없음,차왕모터스,경기 수원시,37.263332,127.028747,"['주차감지센서', '알루미늄휠']",2
3107,22694030,경기,07수7655,르노삼성,국산,트위지,르노삼성 트위지,EV 카고,1046,450,2019,33,57,4757,전기,49,456,경차,0,흰색,오토,없음,없음,없음,1,없음,블루오토,경기 수원시,37.263332,127.028747,['주차감지센서'],1
3133,22926426,경기,59너6793,르노삼성,국산,트위지,르노삼성 트위지,EV 라이프,1363,450,2020,13,67,389,전기,651,1025,경차,129,흰색,오토,없음,없음,있음,1,없음,(주)케이원카,경기 수원시,37.263332,127.028747,['주차감지센서'],1
3432,22859488,경기,69나4586,르노삼성,국산,트위지,르노삼성 트위지,EV 인텐스,1500,390,2018,48,74,17769,전기,147,447,경차,0,흰색,오토,없음,없음,없음,1,없음,뉴제이모터스,경기 수원시,37.263332,127.028747,"['썬루프', '내비게이션', '스마트키', '주차감지센서', '가죽시트', '하이...",8
3695,22812193,경기,57부6521,르노삼성,국산,트위지,르노삼성 트위지,EV 인텐스,1368,520,2020,26,62,4205,전기,922,1258,경차,0,인기색상,오토,없음,없음,없음,1,없음,주식회사 오토프라임,경기 수원시,37.263332,127.028747,"['주차감지센서', '알루미늄휠']",2
4356,22612251,경기,15저1138,르노삼성,국산,트위지,르노삼성 트위지,EV 인텐스,1322,410,2020,21,69,7961,전기,329,480,경차,0,은색,오토,없음,없음,없음,0,없음,하이모터스,경기 수원시,37.263332,127.028747,['주차감지센서'],1
4706,22337255,인천,10소1623,르노삼성,국산,트위지,르노삼성 트위지,EV 라이프,1250,350,2019,34,72,4866,전기,309,444,경차,0,흰색,오토,없음,없음,없음,4,없음,OK자동차매매상사,인천광역시 남동구,37.446902,126.731513,['주차감지센서'],1
43203,22717276,경기,66라4857,르노삼성,국산,트위지,르노삼성 트위지,EV 라이프,1258,390,2020,28,69,4468,전기,685,1058,경차,129,흰색,CVT,없음,없음,없음,2,없음,코리아모터스,경기 수원시,37.263332,127.028747,[],0
43226,22684501,경기,48머8018,르노삼성,국산,트위지,르노삼성 트위지,EV 라이프,1333,360,2019,32,73,8700,전기,49,519,경차,129,흰색,CVT,없음,없음,없음,3,없음,수성자동차,경기 수원시,37.263332,127.028747,['주차감지센서'],1
43234,22730101,경기,04다5567,르노삼성,국산,트위지,르노삼성 트위지,EV 카고,1500,420,2019,37,72,1827,전기,163,446,경차,129,흰색,CVT,없음,없음,없음,2,없음,수성자동차,경기 수원시,37.263332,127.028747,['주차감지센서'],1
43279,22896721,경기,65부2556,르노삼성,국산,트위지,르노삼성 트위지,EV 라이프,1275,370,2020,20,71,25322,전기,422,907,경차,129,흰색,CVT,없음,없음,없음,2,없음,수성자동차,경기 수원시,37.263332,127.028747,"['주차감지센서', '가죽시트']",2
43347,22715233,경기,32소7717,르노삼성,국산,트위지,르노삼성 트위지,EV 인텐스,1464,410,2018,43,72,9774,전기,365,737,경차,129,검정색,CVT,없음,없음,없음,0,없음,코리아모터스,경기 수원시,37.263332,127.028747,[],0
43354,22773484,경기,65부8811,르노삼성,국산,트위지,르노삼성 트위지,EV 라이프,1191,429,2020,20,64,6684,전기,653,1026,경차,129,흰색,CVT,없음,없음,없음,7,있음,코리아모터스,경기 수원시,37.263332,127.028747,[],0

In [54]:
# 중고차 DataFrame에서 'car_model' 빈 부분 찾기

df[df['car_model'] =='']['car_name'].unique()

array(['쌍용 렉카', '지프 체로키', '미니 쿠퍼', '미니 컨트리맨', '마세라티 뉴 기블리', '미니 뉴 클럽맨',
       '미니 쿠퍼 3도어', '캐딜락 ATS', '렉서스 RX', '지프 랭글러', '렉서스 뉴 ES',
       '미니 쿠퍼 5도어', '지프 그랜드 체로키', '캐딜락 CT6', '지프 레니게이드', '미니 쿠퍼 컨버터블',
       '렉서스 NX', '인피니티 G37', '렉서스 LS', '마세라티 콰트로포르테', '인피니티 Q50',
       '링컨 노틸러스', '인피니티 Q70', '렉서스 ES', '인피니티 G25', '캐딜락 CT5', '쉐보레 콜로라도',
       '링컨 MKS', '벤틀리 플라잉스퍼 1세대', '지프 뉴 컴패스', '마세라티 기블리', '링컨 뉴 MKZ',
       '지프 글래디에이터', '링컨 컨티넨탈 10세대', '캐딜락 XT5', '인피니티 EX35', '지프 랭글러 (JL)',
       '미니 쿠퍼 로드스터', '링컨 MKC', '렉서스 뉴 LS', '인피니티 M35', '애스턴마틴 밴티지',
       '캐딜락 CTS 3세대', '렉서스 CT', '미니 클럽맨', '닷지 챌린저', '페라리 488 스파이더',
       '테슬라 Model 3', '렉서스 뉴 RX', '미니 뉴 컨트리맨 (F60)', '렉서스 RC',
       '제네시스 G80(DH)', '렉서스 GS', '제네시스 G80(RG3)', '제네시스 EQ900',
       '제네시스 G70', '지프 컴패스', '인피니티 M37', '제네시스 G90', '제네시스 G70 SPORT',
       '렉서스 뉴 제너레이션 ES', '제네시스 G80 SPORT', '제네시스 GV80', '미니 페이스맨',
       '인피니티 QX70', '닷지 램 픽업', '링컨 뉴 MKS', 'BMW 그란투리스모',
       '캐딜락 ESCALADE(4세대)', '미니 뉴 컨버터블', '인피니티 QX30', '도요타 RAV4',
       '렉서스 뉴 IS', '제네시스 더 뉴 G70', '로버 미니', '링컨 MKX 2세대', '마세라티 르반떼',
       '인피니티 G35', '쉐보레 익스프레스밴', '벤츠 뉴 E클래스', '벤츠 GLE', '벤츠 E클래스 (W213)',
       '벤츠 뉴 C클래스', '벤츠 CLA클래스', '벤츠 더 뉴 C클래스', '벤츠 뉴 S클래스', 'MAN 트럭',
       '벤츠 CLA클래스(C118)', '벤츠 CLS클래스(W218)', '벤츠 CLS클래스(W219)',
       '지프 체로키(KL)', '벤츠 뉴 M클래스', '벤츠 A클래스(W177)', '벤츠 GLE (V167)',
       '렉서스 IS', '벤츠 CLS클래스(C257)', '벤츠 SLC클래스 (R172)', '벤츠 C클래스',
       '인피니티 Q30', '벤츠 B클래스 W246', '벤츠 CLK클래스', '링컨 에비에이터 2세대(U611)',
       '벤츠 A클래스', '벤츠 V클래스', '벤츠 E클래스', '벤츠 E클래스 (C238)', '제네시스 GV70',
       '허머 H3', '스즈키 허슬러', '지프 올뉴 컴패스', '링컨 뉴 MKX', '벤츠 GLA H247',
       '캐딜락 ESCALADE(1~3세대)', '벤츠 S클래스', '캐딜락 올 뉴 SRX', '벤츠 S클래스 W223',
       '벤츠 뉴 SLK클래스', '벤츠 GLS', '벤츠 B클래스', '벤츠 GLK클래스', '벤츠 M클래스',
       '페라리 F430', '벤틀리 벤테이가', '벤츠 G클래스', '테슬라 Model X', '쉐보레 서버밴',
       '링컨 타운카', '링컨 코세어', '인피니티 QX60', '맥라렌 720S', '렉서스 UX',
       '벤틀리 컨티넨탈 플라잉스퍼', '벤츠 스마트', '어큐라 MDX', '닷지 다코타',
       '벤틀리 뉴 컨티넨탈 플라잉스퍼', '도요타 뉴 RAV4', '제네시스 더 뉴 G70 SPORT', '캐딜락 XT6',
       '렉서스 LS 5세대', '인피니티 QX50', '크라이슬러 그랜드보이저', '인피니티 Q60', '인피니티 JX35',
       '미니 쿠페', '스바루 포레스터', '캐딜락 CTS 2세대', '벤츠 뉴 CL클래스', '인피니티 올 뉴 FX',
       '인피니티 EX30d', '마세라티 그란투리스모', '포르쉐 Taycan', '캐딜락 CT4',
       '벤틀리 뉴 컨티넨탈 GT', '동풍자동차 ix5', '벤틀리 컨티넨탈-GT', '벤츠 SLK클래스',
       '인피니티 QX50 2세대', '렉서스 뉴 GS', '한국GM 프리마', '링컨 MKX', '캐딜락 드빌',
       '벤틀리 플라잉스퍼 2세대', '스마트 포투 쿠페', '벤틀리 플라잉스퍼 3세대', '한국GM 레스타',
       '캐딜락 CTS-V', '인피니티 M45', '지프 그랜드 체로키(WL)', '벤츠 SL클래스', '링컨 MKZ',
       '렉서스 LC', '쉐보레 카마로', '벤츠 GL클래스', '캐딜락 ESCALADE(5세대)', '인피니티 FX35',
       '스바루 레거시', '마세라티 그란카브리오', '스마트 포투 카브리오', '람보르기니 아벤타도르',
       '쉐보레 익스플로러밴', 'GMC 시에라', '인피니티 M30d', '허머 H2', '맥라렌 650S',
       '링컨 네비게이터 4세대(U554)', '벤츠 뉴 SL클래스', '마세라티 스파이더', '미니 쿠퍼 S 로드스터',
       'GMC 사바나밴', '중한자동차 KENBO 600', '닷지 캘리버', '인피니티 뉴 FX30d',
       '제네시스 ELECTRIFIED G80', '벤츠 벤츠', '스즈키 스위프트', '스즈키 알토라팡',
       '도요타 SCION', '람보르기니 가야르도', '인피니티 QX80', '캐딜락 CTS 1세대', '스바루 아웃백',
       '캐딜락 리무진', '캐딜락 DTS', '인피니티 뉴 FX35', '도요타 FJ크루저', '캐딜락 STS',
       '인피니티 Q45', '마쯔다 RX시리즈', '애스턴마틴 라피드', '애스턴마틴 DB9', '이베코 기타',
       '쉐보레 이퀴녹스', '캐딜락 ESCALADE', '벤틀리 뮬산', '캐딜락 ALL NEW ESCALADE',
       '람보르기니 우라칸', '닷지 듀랑고', '캐딜락 SRX', '애스턴마틴 뱅퀴시 S', '페라리 캘리포니아',
       '포드 파이브헌드레드', '마세라티 쿠페', '마쯔다 MX-5', '캐딜락 ATS-V', '애스턴마틴 DB11',
       '맥라렌 675LT', '스바루 임프레자 WRX', '맥라렌 570S', '렉서스 SC', '마이바흐 57',
       '지프 커맨더', '벤츠 R클래스', '미쯔비시 렌서에볼루션', '링컨 LS', '벤츠 GLC', '인피니티 QX',
       '벤츠 뉴 CLS클래스', '페라리 FF', '캐딜락 BLS', '마이바흐 62s', '한국GM BS',
       '포톤 툰랜드', '동풍자동차 밴', '한국GM 노부스', '중한자동차 CK 미니 밴', '동풍자동차 소형트럭',
       '한국GM BH', '중한자동차 CK 미니 트럭', '선롱버스 DUEGO', '테슬라 모델 S', '렉서스 뉴 CT',
       '링컨 올 뉴 MKZ', '현대 베뉴', '현대 e-카운티', '현대 현대버스', '현대 뉴카운티',
       '현대 에어로타운', '현대 e-에어로타운 (04년~', '현대 카운티', '현대 유니버스', '기아 라이노',
       '기아 뉴그랜버드'], dtype=object)

## 3. 벤츠 S-클래스 >> 벤츠 S클래스 처리해주기

In [55]:
# 클래스 중간에 하이픈 삭제

search_brand = '벤츠'
model_list2 = youtube_df[youtube_df['car_brand'].str.contains(search_brand)]['car_model'].unique()

for model in model_list2:
    search_model = model.replace('-','')

    model_idx_list = df[(df['car_brand'].str.contains(search_brand))&(df['car_name'].str.contains(search_model))].index

    if len(model_idx_list) > 0:
        for idx in model_idx_list:
            df['car_model'][idx] = search_model

df[df['car_name'].str.contains(search_model)]

/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/strings.py:2001: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

,car_url,car_area,car_no,car_brand,nation,car_model,car_name,name_datailed,new_price,price,year,use,depreciation,mileage,fuel,forecast_min,forecast_max,car_type,car_cc,color,trans,loss,flood,usage,change,insurance,sales_corp,sales_loca,lat,lng,options,options_count
9,22261671,경기,경기91바3367,한국GM,국산,트럭,한국GM 대우트럭,카고,9777,8800,2018,60,10,266862,디젤,4265,4628,트럭,0,검정색,오토,없음,없음,있음,0,없음,(합자)경동자동차매매상사,경기도 평택시,36.992497,127.112717,[],0
11963,22983826,대전,전북86사9281,MAN,수입,,MAN 트럭,카고,10000,7500,2020,20,25,197185,디젤,3273,4076,트럭,4580,흰색,오토,없음,없음,있음,0,없음,대운자동차,대전 유성구,36.362200,127.356300,[],0
18831,22916467,경기,인천83바4106,한국GM,국산,트럭,한국GM 대우트럭,카고,9518,7900,2018,53,17,287128,디젤,4298,4660,트럭,0,회색,오토,없음,없음,있음,0,없음,향남트럭매매,경기도 화성시,37.199465,126.831263,[],0
20746,22889964,경기,89보7009,볼보,수입,트럭,볼보 트럭,윙바디,11126,7900,2017,59,29,514059,디젤,3268,3598,트럭,7698,흰색,오토,없음,없음,있음,2,있음,주식회사 전국화물차매매센터,경기도 시흥시,37.379889,126.803225,[],0
32498,22667537,경기,85조2675,한국GM,국산,트럭,한국GM 대우트럭,압축진개,22500,12600,2018,55,44,80000,디젤,6084,6409,특수,0,갈색,오토,없음,없음,있음,1,없음,세종트럭,경기도 화성시,37.199465,126.831263,['내비게이션'],1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65438,20587165,경기,95버3251,현대,국산,트럭,현대 현대트럭,4.5톤 윙바디,9375,6000,2016,73,36,290000,디젤,4066,5791,트럭,0,흰색,수동,없음,없음,있음,1,없음,주식회사 천지,경기도 화성시,37.199465,126.831263,['알루미늄휠'],1
65597,20375820,경기,89구6467,현대,국산,트럭,현대 3.5톤 트럭,카고 크레인,7849,7300,2008,164,7,250000,디젤,2079,2340,트럭,0,흰색,수동,없음,없음,없음,6,있음,코리아특장,경기도 화성시,37.199465,126.831263,['알루미늄휠'],1
65881,11417704,대전,89마1441,현대,국산,트럭,현대 3.5톤 트럭,덤프,5119,3430,2005,205,33,119337,디젤,2378,3407,트럭,6609,청색,수동,없음,없음,없음,1,없음,(주)대전화물매매상사,대전광역시 서구,36.297392,127.354449,[],0
65884,11410591,광주,95오1454,현대,국산,트럭,현대 현대트럭,덤프트럭(3웨이),17821,4990,2009,163,72,98560,디젤,3388,4731,트럭,8000,노랑,수동,없음,없음,없음,2,없음,(주)시원모터스,광주 서구,35.152140,126.890056,[],0
65927,10058935,경남,89더4748,현대,국산,트럭,현대 현대트럭,5톤 집게차,4081,2490,2006,195,39,329200,디젤,3293,3627,특수,6606,흰색,수동,없음,없음,없음,6,없음,성원자동차매매상사,경남,35.238200,128.692500,[],0

In [56]:
# 중고차 DataFrame에서 'car_model' 빈 부분 찾기

df[df['car_model'] =='']['car_name'].unique()

array(['쌍용 렉카', '지프 체로키', '미니 쿠퍼', '미니 컨트리맨', '마세라티 뉴 기블리', '미니 뉴 클럽맨',
       '미니 쿠퍼 3도어', '캐딜락 ATS', '렉서스 RX', '지프 랭글러', '렉서스 뉴 ES',
       '미니 쿠퍼 5도어', '지프 그랜드 체로키', '캐딜락 CT6', '지프 레니게이드', '미니 쿠퍼 컨버터블',
       '렉서스 NX', '인피니티 G37', '렉서스 LS', '마세라티 콰트로포르테', '인피니티 Q50',
       '링컨 노틸러스', '인피니티 Q70', '렉서스 ES', '인피니티 G25', '캐딜락 CT5', '쉐보레 콜로라도',
       '링컨 MKS', '벤틀리 플라잉스퍼 1세대', '지프 뉴 컴패스', '마세라티 기블리', '링컨 뉴 MKZ',
       '지프 글래디에이터', '링컨 컨티넨탈 10세대', '캐딜락 XT5', '인피니티 EX35', '지프 랭글러 (JL)',
       '미니 쿠퍼 로드스터', '링컨 MKC', '렉서스 뉴 LS', '인피니티 M35', '애스턴마틴 밴티지',
       '캐딜락 CTS 3세대', '렉서스 CT', '미니 클럽맨', '닷지 챌린저', '페라리 488 스파이더',
       '테슬라 Model 3', '렉서스 뉴 RX', '미니 뉴 컨트리맨 (F60)', '렉서스 RC',
       '제네시스 G80(DH)', '렉서스 GS', '제네시스 G80(RG3)', '제네시스 EQ900',
       '제네시스 G70', '지프 컴패스', '인피니티 M37', '제네시스 G90', '제네시스 G70 SPORT',
       '렉서스 뉴 제너레이션 ES', '제네시스 G80 SPORT', '제네시스 GV80', '미니 페이스맨',
       '인피니티 QX70', '닷지 램 픽업', '링컨 뉴 MKS', 'BMW 그란투리스모',
       '캐딜락 ESCALADE(4세대)', '미니 뉴 컨버터블', '인피니티 QX30', '도요타 RAV4',
       '렉서스 뉴 IS', '제네시스 더 뉴 G70', '로버 미니', '링컨 MKX 2세대', '마세라티 르반떼',
       '인피니티 G35', '쉐보레 익스프레스밴', '벤츠 뉴 E클래스', '벤츠 GLE', '벤츠 E클래스 (W213)',
       'MAN 트럭', '지프 체로키(KL)', '벤츠 GLE (V167)', '렉서스 IS', '인피니티 Q30',
       '벤츠 B클래스 W246', '링컨 에비에이터 2세대(U611)', '벤츠 E클래스', '벤츠 E클래스 (C238)',
       '제네시스 GV70', '허머 H3', '스즈키 허슬러', '지프 올뉴 컴패스', '링컨 뉴 MKX',
       '벤츠 GLA H247', '캐딜락 ESCALADE(1~3세대)', '캐딜락 올 뉴 SRX', '벤츠 GLS',
       '벤츠 B클래스', '페라리 F430', '벤틀리 벤테이가', '벤츠 G클래스', '테슬라 Model X',
       '쉐보레 서버밴', '링컨 타운카', '링컨 코세어', '인피니티 QX60', '맥라렌 720S', '렉서스 UX',
       '벤틀리 컨티넨탈 플라잉스퍼', '벤츠 스마트', '어큐라 MDX', '닷지 다코타',
       '벤틀리 뉴 컨티넨탈 플라잉스퍼', '도요타 뉴 RAV4', '제네시스 더 뉴 G70 SPORT', '캐딜락 XT6',
       '렉서스 LS 5세대', '인피니티 QX50', '크라이슬러 그랜드보이저', '인피니티 Q60', '인피니티 JX35',
       '미니 쿠페', '스바루 포레스터', '캐딜락 CTS 2세대', '인피니티 올 뉴 FX', '인피니티 EX30d',
       '마세라티 그란투리스모', '포르쉐 Taycan', '캐딜락 CT4', '벤틀리 뉴 컨티넨탈 GT',
       '동풍자동차 ix5', '벤틀리 컨티넨탈-GT', '인피니티 QX50 2세대', '렉서스 뉴 GS',
       '한국GM 프리마', '링컨 MKX', '캐딜락 드빌', '벤틀리 플라잉스퍼 2세대', '스마트 포투 쿠페',
       '벤틀리 플라잉스퍼 3세대', '한국GM 레스타', '캐딜락 CTS-V', '인피니티 M45',
       '지프 그랜드 체로키(WL)', '링컨 MKZ', '렉서스 LC', '쉐보레 카마로',
       '캐딜락 ESCALADE(5세대)', '인피니티 FX35', '스바루 레거시', '마세라티 그란카브리오',
       '스마트 포투 카브리오', '람보르기니 아벤타도르', '쉐보레 익스플로러밴', 'GMC 시에라', '인피니티 M30d',
       '허머 H2', '맥라렌 650S', '링컨 네비게이터 4세대(U554)', '마세라티 스파이더',
       '미니 쿠퍼 S 로드스터', 'GMC 사바나밴', '중한자동차 KENBO 600', '닷지 캘리버',
       '인피니티 뉴 FX30d', '제네시스 ELECTRIFIED G80', '벤츠 벤츠', '스즈키 스위프트',
       '스즈키 알토라팡', '도요타 SCION', '람보르기니 가야르도', '인피니티 QX80', '캐딜락 CTS 1세대',
       '스바루 아웃백', '캐딜락 리무진', '캐딜락 DTS', '인피니티 뉴 FX35', '도요타 FJ크루저',
       '캐딜락 STS', '인피니티 Q45', '마쯔다 RX시리즈', '애스턴마틴 라피드', '애스턴마틴 DB9',
       '이베코 기타', '쉐보레 이퀴녹스', '캐딜락 ESCALADE', '벤틀리 뮬산',
       '캐딜락 ALL NEW ESCALADE', '람보르기니 우라칸', '닷지 듀랑고', '캐딜락 SRX',
       '애스턴마틴 뱅퀴시 S', '페라리 캘리포니아', '포드 파이브헌드레드', '마세라티 쿠페', '마쯔다 MX-5',
       '캐딜락 ATS-V', '애스턴마틴 DB11', '맥라렌 675LT', '스바루 임프레자 WRX', '맥라렌 570S',
       '렉서스 SC', '마이바흐 57', '지프 커맨더', '미쯔비시 렌서에볼루션', '링컨 LS', '벤츠 GLC',
       '인피니티 QX', '페라리 FF', '캐딜락 BLS', '마이바흐 62s', '한국GM BS', '포톤 툰랜드',
       '동풍자동차 밴', '한국GM 노부스', '중한자동차 CK 미니 밴', '동풍자동차 소형트럭', '한국GM BH',
       '중한자동차 CK 미니 트럭', '선롱버스 DUEGO', '테슬라 모델 S', '렉서스 뉴 CT',
       '링컨 올 뉴 MKZ', '현대 베뉴', '현대 e-카운티', '현대 현대버스', '현대 뉴카운티',
       '현대 에어로타운', '현대 e-에어로타운 (04년~', '현대 카운티', '현대 유니버스', '기아 라이노',
       '기아 뉴그랜버드'], dtype=object)

In [58]:
len(df[df['car_model'] =='']['car_name'].unique())

236

In [61]:
# model명 전처리는 여기까지

df.head(3)

,car_url,car_area,car_no,car_brand,nation,car_model,car_name,name_datailed,new_price,price,year,use,depreciation,mileage,fuel,forecast_min,forecast_max,car_type,car_cc,color,trans,loss,flood,usage,change,insurance,sales_corp,sales_loca,lat,lng,options,options_count
0,22274652,경기,29너6142,한국GM,국산,올란도,한국GM 쉐보레 올란도,LPG LS 일반형,2122,849,2013,103,60,131493,LPG,535,750,RV,0,인기색상,오토,없음,없음,없음,1,있음,주식회사 노빌리티 경기지점,경기 수원시,37.263332,127.028747,[],0
1,22274154,광주,156서1980,한국GM,국산,트랙스,한국GM 더 뉴 트랙스,1.6 디젤 LT 기본형,1986,1450,2018,52,27,60000,디젤,1104,1533,SUV,1598,회색,오토,없음,없음,있음,2,없음,주식회사 즐거운모터스,광주 서구,35.152140,126.890056,"['주차감지센서', '가죽시트', '열선시트', '사이드커튼에어백', '전동접이사이...",7
2,22274071,경기,01서3666,한국GM,국산,스파크,한국GM 더 뉴 스파크,LT 기본형,1423,655,2017,57,54,133319,가솔린,579,818,경차,0,흰색,오토,없음,없음,없음,1,없음,창대모터스,경기 수원시,37.263332,127.028747,"['스마트키', '가죽시트', '알루미늄휠']",3

## 공백은 그냥 car_name에서 car_brand 뺀 데이터로 넣어주자

In [63]:
df.fillna('',inplace = True)
none_index = df[df['car_model'] == ''].index

In [65]:
for idx in none_index:
    df['car_model'][idx] = df['car_name'][idx].replace(f"{df['car_brand'][idx]} ",'')

/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [66]:
df.isnull().sum()

car_url          0
car_area         0
car_no           0
car_brand        0
nation           0
car_model        0
car_name         0
name_datailed    0
new_price        0
price            0
year             0
use              0
depreciation     0
mileage          0
fuel             0
forecast_min     0
forecast_max     0
car_type         0
car_cc           0
color            0
trans            0
loss             0
flood            0
usage            0
change           0
insurance        0
sales_corp       0
sales_loca       0
lat              0
lng              0
options          0
options_count    0
dtype: int64

In [67]:
df.to_csv('usedcar_total_0604.csv', index = False)